---
# tasks file for lamp
- name: apache, mysql and php services installed
  yum:
    name: '{{ pkgs }}'
    state: present
- name: apache service started and enabled 
  service:
    name: httpd
    state: started
    enabled: yes
- name: add httpd services to firewalld
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes
- name: create file index.html file under webservers
  copy:
    dest: /var/www/html/index.html
    content: "Ansible Managed Webservers\n"
    setype: httpd_sys_content_t
  


